spring:
  application:
    name: bank-rest

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # позже будем полагаться на Liquibase для схемы
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

server:
  port: 8080
